apiVersion: v1
kind: Secret
metadata:
  name: usuario-secret
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: c2E=
  SPRING_DATASOURCE_PASSWORD: MTIzNA==
  SPRING_RABBITMQ_USERNAME: ZXZlbnQ=
  SPRING_RABBITMQ_PASSWORD: ZHJpdmVu