spring.application.name=usuario-service

spring.datasource.url=jdbc:h2:mem:usuariosDB
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

#h2
spring.h2.console.settings.web-allow-others=true
spring.h2.console.path=/h2-console
spring.h2.console.enabled=true

#rabitmq
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=event
spring.rabbitmq.password=driven