apiVersion: v1
kind: ConfigMap
metadata:
  name: email-config
data:

  SERVER_PORT: "7070"
  SPRING_MAIL_HOST: "smtp.gmail.com"
  SPRING_MAIL_PORT: "587"

  SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: "true"
  SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: "true"
  SPRING_RABBITMQ_PORT: "5672"
